[project]
name = "spotify_to_ytmusic"
description = "Transfer Spotify playlists to YouTube Music"
requires-python = ">=3.8"
authors=[{name = "sigma67", email= "ytmusicapi@gmail.com"}]
license={file="LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "ytmusicapi",
    "spotipy"
]
dynamic = ["version", "readme"]

[project.optional-dependencies]
dev = ['pre-commit', 'flake8', 'yapf', 'coverage', 'sphinx', 'sphinx-rtd-theme']

[project.scripts]
ytmusicapi = "spotify_to_ytmusic.main:main"

[project.urls]
homepage = "https://github.com/sigma67/spotify_to_ytmusic"
repository = "https://github.com/sigma67/spotify_to_ytmusic"

[build-system]
requires = ["setuptools>=65", "setuptools_scm[toml]>=7"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.setuptools.dynamic]
readme = {file = ["README.rst"]}

[tool.setuptools]
include-package-data=false

[tool.setuptools.package-data]
"*" = ["**.example", "**.py"]

[tool.yapf]
column_limit = 99
split_before_arithmetic_operator = true

[tool.coverage.run]
command_line = "-m unittest discover tests"
